### ISSUE TITLE
Wrong result 10k

### ISSUE THREAD

**Issue by tivrfoa** [lehuyduc/1brc-simd#4]
Hi lehuyduc!

I tested your code locally: 200 million rows for the 10k dataset.
It's getting wrong result.

To check that, run one of the Java first 3 solutions, and compare the output with yours.

Yours is on the right here:

![image](https://github.com/lehuyduc/1brc-simd/assets/30683/265cb035-d6cf-4314-92da-9c4e64c1726d)

**Comment by lehuyduc** [comment]
Could you upload the file for me? I don't have a java env right now. Thanks!

**Comment by lehuyduc** [comment]
Is the file generated by `create_measurement3.sh` deterministic? If not, could you send the first 200M lines file to me? Compressed to .zip it should be < 1GB. Thanks for helping me debug!

**Comment by tivrfoa** [comment]
> Is the file generated by `create_measurement3.sh` deterministic? If not, could you send the first 200M lines file to me? Compressed to .zip it should be < 1GB. Thanks for helping me debug!

I think it's not deterministic, but I guess you'll be able to reproduce that with any dataset generated.
https://www.graalvm.org/downloads/

The zip for the file `./create_measurement3.sh 200000000` is 1.8GB.
Do you have a link where I can upload that?

**Comment by lehuyduc** [comment]
Could you upload to google drive? I'll download then you can delete it 4 hours from now. Thanks a great deal!

If not then I'll try to generate the dataset later.

**Comment by tivrfoa** [comment]
> Could you upload to google drive? I'll download then you can delete it 4 hours from now. Thanks a great deal!
> 
> If not then I'll try to generate the dataset later.

My Internet speed is not good. It's really faster for you to download Java and generate it ... but I'm uploading right now, might take a while

**Comment by tivrfoa** [comment]
Sorry the delay. See if you can access, please:

https://drive.google.com/file/d/1sVA0yUuo5oZoeAQFoPJgaF0cQnq4fPCr/view?usp=sharing

https://drive.google.com/file/d/1hB72HaFC87Pjykv1mu0CIF4kXO5Qjefs/view?usp=sharing

But it's better for you to generate this by yourself.

**Comment by lehuyduc** [comment]
Thanks! That link requires permission (I think you forgot to set it to "anyone with the link"). Could you check please?

**Comment by tivrfoa** [comment]
> Sorry the delay. See if you can access, please:
> 
> https://drive.google.com/file/d/1sVA0yUuo5oZoeAQFoPJgaF0cQnq4fPCr/view?usp=sharing
> 
> https://drive.google.com/file/d/1hB72HaFC87Pjykv1mu0CIF4kXO5Qjefs/view?usp=sharing
> 
> But it's better for you to generate this by yourself.

I gave you access to the files. Try again, please.

**Comment by lehuyduc** [comment]
I've downloaded, you can delete them now. Thanks again!!

I've got some ideas for a new hash map that works both in the easy test and in the 10k keys test :D Maybe I'll update during weekend

**Comment by lehuyduc** [comment]
@tivrfoa eh, which commit did you use to test? I ran with the latest commit, and the result is correct.

**Comment by tivrfoa** [comment]
> @tivrfoa eh, which commit did you use to test? I ran with the latest commit, and the result is correct.

1brc_final_valid.cpp

```
commit b1719828fd6e008bda6f597f5cb7af8839004dd3 (HEAD -> main, origin/main, origin/HEAD)
Author: lehuyduc <lehuyduc3@gmail.com>
Date:   Sat Jan 13 20:48:35 2024 +0700

    Add another benchmark
```

**Comment by lehuyduc** [comment]
That's strange. I'm running that commit and the output sha256sum is `e99d23f6fa210b0d9c43a63e335d8d49f4a247ca7cc237bea0fe4c8b64b1933e` same as `thomas-native-10k.out`.

I wonder what's wrong here

**Comment by lehuyduc** [comment]
Ah, how many threads does your CPU have?

**Comment by tivrfoa** [comment]
> That's strange. I'm running that commit and the output sha256sum is `e99d23f6fa210b0d9c43a63e335d8d49f4a247ca7cc237bea0fe4c8b64b1933e` same as `thomas-native-10k.out`.
> 
> I wonder what's wrong here

I run it again and it matches too. So I probably made some mistake. Maybe I regenerate the dataset ...

Or maybe that output in the first picture was not yours, but from other person ...

Sorry for the noise.

**Comment by tivrfoa** [comment]
> Ah, how many threads does your CPU have?

time ./../1brc-simd/main measurements.txt && mv result.txt out/cpp-lehuyduc-10k.out
Using 8 threads

**Comment by tivrfoa** [comment]
> > @tivrfoa eh, which commit did you use to test? I ran with the latest commit, and the result is correct.
> 
> 1brc_final_valid.cpp
> 
> ```
> commit b1719828fd6e008bda6f597f5cb7af8839004dd3 (HEAD -> main, origin/main, origin/HEAD)
> Author: lehuyduc <lehuyduc3@gmail.com>
> Date:   Sat Jan 13 20:48:35 2024 +0700
> 
>     Add another benchmark
> ```

It was not this commit!

There was this bug indeed, but you fixed it already (maybe in day 13).

I recompiled your solution today, but saved the old binary before. Running the old binary it gives the same error.

I'll try to find which was the fix, just for fun, but there's no bug anymore!!! :D

**Comment by lehuyduc** [comment]
Thanks for helping!

**Comment by lehuyduc** [comment]
@tivrfoa Currently, at 8 thread, `measurements.txt` is ~10% slower (1270 -> 1400), but `measurements_10k.txt` can be run in ~2.7s. It didn't take much more work at all, might try to improve more. The slowndown on the default dataset is really bad though, especially at higher thread numbers 😢 

Thanks for pushing me to work on the 10k version 🤣 I was feeling really lazy.

**Comment by tivrfoa** [comment]
> @tivrfoa Currently, at 8 thread, `measurements.txt` is ~10% slower (1270 -> 1400), but `measurements_10k.txt` can be run in ~2.7s. It didn't take much more work at all, might try to improve more. The slowndown on the default dataset is really bad though, especially at higher thread numbers 😢
> 
> Thanks for pushing me to work on the 10k version 🤣 I was feeling really lazy.

Just to remember that the file I shared contains only 200 million rows for the 10k, instead of 1 billion in the challenge. =D

**Comment by tivrfoa** [comment]
> > > @tivrfoa eh, which commit did you use to test? I ran with the latest commit, and the result is correct.
> > 
> > 
> > 1brc_final_valid.cpp
> > ```
> > commit b1719828fd6e008bda6f597f5cb7af8839004dd3 (HEAD -> main, origin/main, origin/HEAD)
> > Author: lehuyduc <lehuyduc3@gmail.com>
> > Date:   Sat Jan 13 20:48:35 2024 +0700
> > 
> >     Add another benchmark
> > ```
> 
> It was not this commit!
> 
> There was this bug indeed, but you fixed it already (maybe in day 13).
> 
> I recompiled your solution today, but saved the old binary before. Running the old binary it gives the same error.
> 
> I'll try to find which was the fix, just for fun, but there's no bug anymore!!! :D

1brc_valid14.cpp still had the bug. 1brc_valid14b.cpp is correct

**Comment by lehuyduc** [comment]
I tested 1B lines by copying the 200M lines 5 times :D

**Comment by lehuyduc** [comment]
@tivrfoa Just added new version that improves 10k keys performance. It's only ~2x slower now, instead of 4-5x.

If you're interested, please test with some new data :D Difference between `valid17` and `valid18` is that, `valid18` intentionally uses fewer threads than available (practically equal to disabling hyper threading) when hash collision is likely. Improves performance by like ~20% compared to running at max number of threads.

**Comment by tivrfoa** [comment]
> @tivrfoa Just added new version that improves 10k keys performance. It's only ~2x slower now, instead of 4-5x.
> 
> If you're interested, please test with some new data :D Difference between `valid17` and `valid18` is that, `valid18` intentionally uses fewer threads than available (practically equal to disabling hyper threading) when hash collision is likely. Improves performance by like ~20% compared to running at max number of threads.

Wow! Really cool! =D

I'll test. Amazing work!

**Comment by lehuyduc** [comment]
@tivrfoa I just pushed my final version, another ~20% improvement.

If the dataset fit inside your RAM, could you please run a few other top solutions on your env and make a comparison table? It seems you already have everything setup. Thanks!

**Comment by tivrfoa** [comment]
> @tivrfoa I just pushed my final version, another ~20% improvement.
> 
> If the dataset fit inside your RAM, could you please run a few other top solutions on your env and make a comparison table? It seems you already have everything setup. Thanks!

I have little RAM, so I test only 200 million rows.

Ubuntu
AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx

avx, avx2

# Normal dataset: 2,6G

## Fastest Java:

```
time ./target/CalculateAverage_thomaswue_image > ok.out

real	0m0,797s
user	0m4,382s
sys	0m0,499s
```

## Your code:

```
time ./../1brc-simd/main measurements.txt

real	0m0,633s
user	0m2,954s
sys	0m0,612s
```

# 10k: 3,2G

## Fastest Java:

```
time ./target/CalculateAverage_thomaswue_image > ok.out

real	0m4,699s
user	0m32,952s
sys	0m0,905s
```

## Your code:

```
time ./../1brc-simd/main measurements.txt

real	0m3,095s
user	0m20,252s
sys	0m0,986s
```

# CPU 8 cores

Which of the CPU flags below is your code using?

```
vendor_id   : AuthenticAMD                                                         
cpu family  : 23                                                                   
model       : 24                                                                
model name  : AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx                     
stepping    : 1                                                                 
microcode   : 0x8108102                                                         
cpu MHz     : 1245.611                                                          
cache size  : 512 KB                                                            
physical id : 0                                                                 
siblings    : 8                                                                 
core id     : 0                                                                 
cpu cores   : 4                                                                 
apicid      : 0                                                                 
initial apicid  : 0                                                             
fpu     : yes                                                                   
fpu_exception   : yes                                                           
cpuid level : 13                                                                
wp      : yes                                                                   
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sev sev_es
bugs        : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso div0
bogomips    : 4192.27                                                           
TLB size    : 2560 4K pages                                                     
clflush size    : 64                                                            
cache_alignment : 64                                                            
address sizes   : 43 bits physical, 48 bits virtual                             
power management: ts ttp tm hwpstate eff_freq_ro [13] [14] 
```

**Comment by lehuyduc** [comment]
I'm using just avx, avx2.

The results look about as expected, thanks!
